<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
        <parent>
            <groupId>fi.nls.hakunapi</groupId>
            <artifactId>hakunapi</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </parent>
	<artifactId>src-community</artifactId>
	<packaging>pom</packaging>
	<modules>
		<module>hakunapi-gml</module>
		<module>hakunapi-proj-jhe</module>
		<module>hakunapi-smile</module>
		<module>hakunapi-esbulk</module>
		<module>hakunapi-tiles-core</module>
		<module>hakunapi-tiles-source-vectortile</module>
		<module>hakunapi-tiles-source-wmts</module>
		<module>hakunapi-tiles-source-gpkg</module>
		<module>hakunapi-tiles-source-pmtiles</module>
		<module>hakunapi-tiles-servlet-jakarta</module>
	</modules>
</project>
