package fi.nls.hakunapi.source.gpkg.http.vfs;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.Test;

/**
 * The block reader's contract: identical bytes to reading through, and fewer
 * reads of the thing underneath.
 */
public class BlockCacheRangeReaderTest {

    private static final int SIZE = 1 << 20;

    /** A RangeReader over generated bytes that counts the reads it is asked for. */
    private static class CountingReader implements RangeReader {

        private final byte[] data;
        private final AtomicInteger reads = new AtomicInteger();

        CountingReader(int size) {
            this.data = new byte[size];
            for (int i = 0; i < size; i++) {
                data[i] = (byte) (i * 31 + (i >> 8));
            }
        }

        @Override
        public int read(long srcOffset, byte[] dst, int dstOff, int len) {
            reads.incrementAndGet();
            int n = (int) Math.min(len, data.length - srcOffset);
            if (n <= 0) {
                return 0;
            }
            System.arraycopy(data, (int) srcOffset, dst, dstOff, n);
            return n;
        }

        @Override
        public long size() {
            return data.length;
        }

        @Override
        public void close() {
        }
    }

    /** The bytes a plain read of the same range would produce. */
    private static byte[] expected(int size, long offset, int len) {
        byte[] b = new byte[len];
        new CountingReader(size).read(offset, b, 0, len);
        return b;
    }

    @Test
    public void servesTheSameBytesAsReadingThrough() throws Exception {
        CountingReader src = new CountingReader(300_000);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 4096, 1 << 20)) {
            // mid-block, on a boundary, spanning blocks, and at the end
            long[][] cases = { {0, 100}, {4095, 2}, {4096, 4096}, {5000, 9000}, {299_000, 1000} };
            for (long[] c : cases) {
                int len = (int) c[1];
                byte[] actual = new byte[len];
                int n = r.read(c[0], actual, 0, len);
                assertEquals("length at " + c[0], len, n);
                assertArrayEquals("bytes at " + c[0], expected(300_000, c[0], len), actual);
            }
        }
    }

    @Test
    public void readsSpanningBlocksAreStitchedTogether() throws Exception {
        CountingReader src = new CountingReader(100_000);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 1024, 1 << 20)) {
            byte[] actual = new byte[5000];
            assertEquals(5000, r.read(500, actual, 0, 5000));
            assertArrayEquals(expected(100_000, 500, 5000), actual);
            // 500..5500 touches blocks 0..5: six fetches, no more
            assertEquals(6, r.misses());
        }
    }

    @Test
    public void sequentialPageReadsCostOneFetchPerBlock() throws Exception {
        CountingReader src = new CountingReader(SIZE);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 64 * 1024, 1 << 20)) {
            byte[] page = new byte[4096];
            for (int i = 0; i < 16; i++) { // one 64 KiB block covers 16 pages
                r.read(i * 4096L, page, 0, 4096);
            }
            assertEquals("one fetch for sixteen pages", 1, r.misses());
            assertEquals(15, r.hits());
            assertEquals("and one read of the source", 1, src.reads.get());
        }
    }

    @Test
    public void evictsOldestBlocksWhenFull() throws Exception {
        CountingReader src = new CountingReader(SIZE);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 4096, 2 * 4096)) {
            byte[] page = new byte[4096];
            r.read(0, page, 0, 4096);
            r.read(4096, page, 0, 4096);
            r.read(8192, page, 0, 4096); // evicts block 0
            assertEquals(3, r.misses());
            r.read(0, page, 0, 4096);
            assertEquals("block 0 was evicted", 4, r.misses());
        }
    }

    @Test
    public void readingPastEndOfFileReturnsZero() throws Exception {
        CountingReader src = new CountingReader(10_000);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 4096, 1 << 20)) {
            byte[] dst = new byte[100];
            assertEquals(0, r.read(10_000, dst, 0, 100));
            assertEquals("a read up to the end is served", 100, r.read(9900, dst, 0, 100));
            assertEquals("and one past it is clamped", 50, r.read(9950, dst, 0, 100));
        }
    }

    @Test
    public void servesTheSegmentPath() throws Exception {
        CountingReader src = new CountingReader(100_000);
        try (Arena arena = Arena.ofConfined();
                BlockCacheRangeReader r = new BlockCacheRangeReader(src, 4096, 1 << 20)) {
            MemorySegment dst = arena.allocate(5000);
            assertEquals(5000, r.read(3000, dst, 5000));
            assertArrayEquals(expected(100_000, 3000, 5000), dst.toArray(ValueLayout.JAVA_BYTE));
        }
    }

    @Test
    public void blockSizeIsRoundedToAPowerOfTwo() throws Exception {
        CountingReader src = new CountingReader(SIZE);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 5000, 1 << 20)) {
            byte[] page = new byte[4096];
            r.read(0, page, 0, 4096);    // rounded up to 8192, so pages 0 and 1
            r.read(4096, page, 0, 4096); // share one block
            assertEquals(1, r.misses());
        }
    }

    /** Concurrent readers must all see correct bytes; the sqlite3 handle is shared. */
    @Test
    public void isSafeUnderConcurrentReads() throws Exception {
        CountingReader src = new CountingReader(SIZE);
        AtomicReference<Exception> failure = new AtomicReference<>();
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 8192, 64 * 1024)) {
            Thread[] ts = new Thread[8];
            for (int t = 0; t < ts.length; t++) {
                final int seed = t;
                ts[t] = new Thread(() -> {
                    byte[] buf = new byte[4096];
                    try {
                        for (int i = 0; i < 200; i++) {
                            long off = (seed * 7919L + i * 4096L) % SIZE & ~3L;
                            int len = (int) Math.min(4096, SIZE - off);
                            int n = r.read(off, buf, 0, len);
                            byte[] want = expected(SIZE, off, len);
                            for (int k = 0; k < n; k++) {
                                if (buf[k] != want[k]) {
                                    throw new IOException("mismatch at " + (off + k));
                                }
                            }
                        }
                    } catch (Exception e) {
                        failure.compareAndSet(null, e);
                    }
                });
            }
            for (Thread t : ts) {
                t.start();
            }
            for (Thread t : ts) {
                t.join();
            }
        }
        assertEquals(null, failure.get());
    }

    @Test
    public void countsHitsAndMisses() throws Exception {
        CountingReader src = new CountingReader(SIZE);
        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 4096, 1 << 20)) {
            byte[] page = new byte[4096];
            r.read(0, page, 0, 4096);
            r.read(0, page, 0, 4096);
            r.read(0, page, 0, 4096);
            assertEquals(1, r.misses());
            assertEquals(2, r.hits());
            assertTrue(r.size() > 0);
        }
    }


    /**
     * Many threads wanting the same block issue one request between them. The
     * reader underneath is held inside the read until every thread has arrived,
     * so a pass cannot come from the fetch simply finishing first.
     */
    @Test
    public void coalescesConcurrentMissesOfTheSameBlock() throws Exception {
        int threads = 8;
        CountDownLatch arrived = new CountDownLatch(threads);
        AtomicInteger reads = new AtomicInteger();
        RangeReader src = new RangeReader() {

            private final CountingReader data = new CountingReader(SIZE);

            @Override
            public int read(long srcOffset, byte[] dst, int dstOff, int len) throws IOException {
                reads.incrementAndGet();
                try {
                    // Every thread is either waiting on this block or about to
                    // be; if one of them fetched too, this would never return.
                    arrived.await();
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    throw new IOException(e);
                }
                return data.read(srcOffset, dst, dstOff, len);
            }

            @Override
            public long size() {
                return SIZE;
            }

            @Override
            public void close() {
            }
        };

        try (BlockCacheRangeReader r = new BlockCacheRangeReader(src, 4096, 1 << 20)) {
            AtomicReference<Exception> failed = new AtomicReference<>();
            Thread[] ts = new Thread[threads];
            for (int i = 0; i < threads; i++) {
                ts[i] = new Thread(() -> {
                    byte[] dst = new byte[100];
                    try {
                        arrived.countDown();
                        r.read(1000, dst, 0, dst.length);
                        assertArrayEquals(expected(SIZE, 1000, 100), dst);
                    } catch (Exception e) {
                        failed.compareAndSet(null, e);
                    }
                });
                ts[i].start();
            }
            for (Thread t : ts) {
                t.join(30_000);
            }
            assertEquals(null, failed.get());
            assertEquals(1, reads.get());
            assertEquals(1, r.misses());
            assertEquals(threads - 1, r.hits());
        }
    }

}
